name: "build"
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: self-hosted
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v6"
      - name: "setup jdk"
        uses: "actions/setup-java@v5"
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: "setup gradle"
        uses: gradle/actions/setup-gradle@v5
      - name: "make gradle wrapper executable"
        run: chmod +x ./gradlew
      - name: "build plugin"
        run: "./gradlew :plugin:build"
      - name: "build tester"
        run: "./gradlew :tester:build"
      - name: "publish to github packages"
        if: "${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) }}"
        run: ./gradlew :plugin:publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_ACTOR: "${{ secrets.WEHEBA_ORG_USERNAME || github.actor }}"
          GITHUB_TOKEN: "${{ secrets.WEHEBA_ORG_TOKEN || secrets.GITHUB_TOKEN }}"
